# Generated by Django 6.0.7 on 2026-07-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryApp', '0003_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Categoryname',
            new_name='categoryname',
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
