# Generated by Django 6.0.7 on 2026-08-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryApp', '0014_order_tracking_status_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='India', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='currency_code',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='currency_symbol',
            field=models.CharField(default='₹', max_length=10),
        ),
    ]
