# Generated by Django 6.0.7 on 2026-08-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryApp', '0015_customer_country_customer_currency_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country_code',
            field=models.CharField(default='IN', max_length=10),
        ),
    ]
